-- Use this plugin if you dont want to install yazi file manager
-- Uncomment below to use telescope file browser instead of yazi

return {
	-- {
	-- 	"nvim-telescope/telescope-file-browser.nvim",
	-- 	dependencies = {
	-- 		"nvim-telescope/telescope.nvim",
	-- 		"nvim-lua/plenary.nvim",
	-- 	},
	-- 	keys = {
	-- 		{
	-- 			"fa",
	-- 			function()
	-- 				require('telescope').extensions.file_browser.file_browser({
	-- 					initial_mode = "normal"
	-- 				})
	-- 			end,
	-- 			desc = "File Browser"
	-- 		},
	-- 		{
	-- 			"fj",
	-- 			function()
	-- 				require('telescope').extensions.file_browser.file_browser({
	-- 					initial_mode = "normal",
	-- 					select_buffer = true,
	-- 					path = "%:p:h",
	-- 					hidden = true
	-- 				})
	-- 			end,
	-- 			desc = "File Browser (current file)"
	-- 		},
	-- 	},
	-- },
}
